# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75502eb4ec99cc916d0203e4d7e96fd1d444ba8f63f23390f0feb11b59bc250b6ebb2d5eece6df6a25ad3a632b6f4fa61bc4f31e2f258d3b0e0e857bc7576518

test:
  secret_key_base: a62e87367badae819dc5a4e4da301fee5e9ed2dd1892a3bcfd436f33a5703b65f735d97b9c7a195a41e5216db744146c207e5c5dfaf2debf005297fc15cb8426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
